#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("COMP231_W2020_OnDuty.Resource", IsApplication=true)]

namespace COMP231_W2020_OnDuty
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int province_array = 2130771968;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int colorAccent = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int colorPrimary = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int colorPrimaryDark = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int ic_launcher_background = 2130837507;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int buttonLogin = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int buttonSignUp = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int editTextPassword = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int linearLayout1 = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int radioButtonRegularUser = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int radioButtonServiceProvider = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int spinnerProvince = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int textInputEditTextAddress = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int textInputEditTextCity = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int textInputEditTextMobile = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int textInputEditTextName = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int textInputEditTextPassword = 2130903051;
			
			// aapt resource value: 0x7F03000D
			public const int textInputEditTextUsername = 2130903053;
			
			// aapt resource value: 0x7F03000C
			public const int textInputEditTextUserName = 2130903052;
			
			// aapt resource value: 0x7F03000E
			public const int textInputEditTextZipcode = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int textView1 = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int textViewAppName = 2130903056;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040002
			public const int activity_main = 2130968578;
			
			// aapt resource value: 0x7F040000
			public const int CreateAccount = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Login = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int ic_launcher = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ic_launcher_foreground = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ic_launcher_round = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int action_settings = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int province_prompt = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
